apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-engine
  namespace: inference-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-engine
  template:
    metadata:
      labels:
        app: inference-engine
    spec:
      containers:
        - name: app
          image: inference-engine:latest
          ports:
            - containerPort: 8000
