apiVersion: v1
kind: Service
metadata:
  name: inference-engine
  namespace: inference-engine
spec:
  selector:
    app: inference-engine
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
